apiVersion: v1
kind: Service
metadata:
  name: enrollment-service
  namespace: online-learning-platform
spec:
  selector:
    app: enrollment-service
  ports:
    - name: http
      port: 80
      targetPort: 8085
    - name: grpc
      port: 9099
      targetPort: 9099
  type: ClusterIP
