package org.sleepless_artery.submission_service.logging.event;


public enum LogEvent {
    SUBMISSION_FETCH,
    SUBMISSION_NOT_FOUND,
    SUBMISSION_CREATION,
    SUBMISSION_UPDATE,
    SUBMISSION_DELETION,
    SUBMISSION_DELETION_BY_ASSIGNMENT_ID,
    SUBMISSION_DELETION_BY_STUDENT_ID,
    REVIEW_SUBMISSION_UPDATE,
    REVIEW_SUBMISSION_DELETION,
    FILE_VALIDATION,
    FILE_UPLOAD,
    FILE_REMOVE,
    FILE_DOWNLOAD,
    FILE_URL_GENERATION,
    EXISTENCE_VALIDATION
}
