apiVersion: v1
kind: Service
metadata:
  name: postgres-lessons
  namespace: online-learning-platform
  labels:
    app: postgres-lessons
spec:
  ports:
    - port: 5432
      name: postgres-lessons
  clusterIP: None
  selector:
    app: postgres-lessons