package org.sleepless_artery.auth_service.common.logging.event;

public enum LogEvent {
    CREATION_AUTHENTICATION_TOKEN,
    CREATION_CREDENTIAL,
    DELETION_CREDENTIAL,
    ADDING_ROLE_FOR_USER,
    DELETING_ROLE_FOR_USER,
    EMAIL_RESERVATION,
    EMAIL_CHANGE,
    EMAIL_CONFIRMATION,
    CONFIRMATION_CODE_VERIFICATION,
    REGISTRATION_INITIALIZATION,
    REGISTRATION_CONFIRMATION,
    PASSWORD_RESET_INITIALIZATION,
    PASSWORD_RESET_CODE_VERIFICATION,
    PASSWORD_RESET_COMPLETION,
    EMAIL_CONFIRMATION_SENDING
}
