apiVersion: v1
kind: Service
metadata:
  name: postgres-auth
  namespace: online-learning-platform
  labels:
    app: postgres-auth
spec:
  ports:
    - port: 5432
      name: postgres-auth
  clusterIP: None
  selector:
    app: postgres-auth