apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment-service
  namespace: online-learning-platform
  labels:
    app: assignment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assignment-service
  template:
    metadata:
      labels:
        app: assignment-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for postgres..."
              until nc -z postgres-assignments 5432; do
                sleep 2
              done
              echo "Postgres is available"
      containers:
        - name: assignment-service
          image: arterygin/assignment-service:1.0.58
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8087
          
          envFrom:
            - configMapRef:
                name: assignment-config
            - secretRef:
                name: assignment-secret
          
          readinessProbe:
            httpGet:
              path: /internal/actuator/health/readiness
              port: 8087
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /internal/actuator/health/liveness
              port: 8087
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1"
          
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false

      restartPolicy: Always
