apiVersion: v1
kind: ConfigMap
metadata:
  name: lesson-config
  namespace: online-learning-platform
data:
  SPRING_PROFILES_ACTIVE: kubernetes

  SPRING_JPA_HIBERNATE_DDL_AUTO: update

  LESSON_DB_URL: jdbc:postgresql://postgres-lessons:5432/lesson_db

  COURSE_SERVICE_GRPC_URL: course-service:9095
  
  LESSON_REDIS_HOST: redis-lessons

  KAFKA_BOOTSTRAP_SERVERS: kafka-kafka-bootstrap:9092