apiVersion: v1
kind: Service
metadata:
  name: lesson-service
  namespace: online-learning-platform
spec:
  selector:
    app: lesson-service
  ports:
    - name: http
      port: 80
      targetPort: 8084
    - name: grpc
      port: 9097
      targetPort: 9097
  type: ClusterIP
