apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: online-learning-platform
data:
  SPRING_PROFILES_ACTIVE: kubernetes

  AUTH_DB_URL: jdbc:postgresql://postgres-auth:5432/auth_db

  USER_SERVICE_GRPC_URL: user-service:9093
  
  AUTH_REDIS_HOST: redis-auth

  KAFKA_BOOTSTRAP_SERVERS: kafka-kafka-bootstrap:9092