apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: online-learning-platform
data:
  SPRING_PROFILES_ACTIVE: kubernetes

  USER_DB_URL: jdbc:postgresql://postgres-users:5432/user_db

  AUTH_SERVICE_GRPC_URL: auth-service:9091

  COURSE_SERVICE_GRPC_URL: course-service:9095

  ENROLLMENT_SERVICE_GRPC_URL: enrollment-service:9099
  
  USER_REDIS_HOST: redis-users

  KAFKA_BOOTSTRAP_SERVERS: kafka-kafka-bootstrap:9092

  SPRING_JPA_HIBERNATE_DDL_AUTO: update