apiVersion: v1
kind: Service
metadata:
  name: course-service
  namespace: online-learning-platform
spec:
  selector:
    app: course-service
  ports:
    - name: http
      port: 80
      targetPort: 8083
    - name: grpc
      port: 9095
      targetPort: 9095
  type: ClusterIP
