apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-assignments
  namespace: online-learning-platform
spec:
  serviceName: postgres-assignments
  replicas: 1
  selector:
    matchLabels:
      app: postgres-assignments
  template:
    metadata:
      labels:
        app: postgres-assignments
    spec:
      containers:
        - name: postgres-assignments
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: assignment-secret
                  key: ASSIGNMENT_DB_USERNAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: assignment-secret
                  key: ASSIGNMENT_DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: assignment-secret
                  key: ASSIGNMENT_DB_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "$(POSTGRES_USER)"]
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 6

          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "$(POSTGRES_USER)"]
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 6

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
              
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi