FROM eclipse-temurin:21-jdk-jammy as builder
WORKDIR /app
COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN ./mvnw dependency:go-offline

COPY src ./src
RUN ./mvnw clean package -DskipTests
RUN rm -rf .mvn mvnw pom.xml

FROM eclipse-temurin:21-jre-jammy as runtime
WORKDIR /app

COPY --from=builder /app/target/user-service-*.jar app.jar
COPY src/main/resources/db/migration/ /app/resources/db/migration/

ENV JAVA_OPTS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError"

ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar /app/app.jar"]